FROM bellsoft/liberica-openjdk-debian:21

# скопировать все файлы из локальной машины в app
COPY capitalize/build/output-docker/capitalize.jar /app/

# задать рабоч директорию
WORKDIR /app

ENTRYPOINT ["java", "-jar" ,"capitalize.jar"]