FROM bellsoft/liberica-openjdk-debian:21

# скопировать все файлы из локальной машины в app
COPY upper/build/output-docker/upper.jar /app/

# задать рабоч директорию
WORKDIR /app

ENTRYPOINT ["java", "-jar" ,"upper.jar"]